name: Build LaTeX document
on: [push]

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: tephyna.tex

